-- =====================================================
-- Edu-Hub Data Connect - Supabase Database Schema
-- =====================================================
-- This schema matches Hubnet's structure but branded for Edu-Hub Data
-- Run this in the Supabase SQL Editor after creating your project
-- =====================================================

-- =====================================================
-- 1. Users & Authentication
-- =====================================================
create table profiles (
  id uuid primary key references auth.users not null,
  full_name text,
  phone text,
  balance numeric(12,2) default 0.00,
  role text default 'reseller',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

comment on table profiles is 'User profiles linked to Supabase auth.users';
comment on column profiles.balance is 'Current wallet balance in GH¢';
comment on column profiles.role is 'User role: reseller, admin, etc.';

-- =====================================================
-- 2. Wallet Transactions
-- =====================================================
create table wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount numeric(12,2) not null,
  type text check (type in ('credit', 'debit')),
  description text,
  reference text unique,
  status text default 'completed',
  created_at timestamp with time zone default now()
);

comment on table wallet_transactions is 'All wallet credit/debit transactions';
comment on column wallet_transactions.type is 'credit = money added, debit = money spent';
comment on column wallet_transactions.reference is 'Unique transaction reference (e.g., payment gateway ref)';

-- =====================================================
-- 3. Data Bundle Orders
-- =====================================================
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  order_id text unique not null, -- e.g. #3991038
  network text not null, -- MTN, AT, Telecel
  msisdn text not null,
  package text not null,
  amount numeric(12,2) not null, -- what customer paid
  cost numeric(12,2) not null, -- what we paid the API
  profit numeric(12,2) generated always as (amount - cost) stored,
  status text default 'pending' check (status in ('pending', 'delivered', 'failed', 'refunded')),
  api_response jsonb,
  created_at timestamp with time zone default now()
);

comment on table orders is 'Data bundle purchase orders';
comment on column orders.order_id is 'Human-readable order ID (e.g., #3991038)';
comment on column orders.network is 'Telecom network: MTN, AT (AirtelTigo), Telecel';
comment on column orders.msisdn is 'Customer phone number';
comment on column orders.package is 'Data package name (e.g., 1GB Daily, 10GB Monthly)';
comment on column orders.amount is 'Amount charged to customer in GH¢';
comment on column orders.cost is 'Cost paid to API provider in GH¢';
comment on column orders.profit is 'Automatically calculated profit (amount - cost)';
comment on column orders.api_response is 'Raw API response from telecom provider';

-- =====================================================
-- 4. Data Bundle Packages
-- =====================================================
create table bundles (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('MTN', 'AT_ISHARE', 'AT_BIGTIME', 'TELECEL', 'MTN_UP2U')),
  display_name text not null,        -- e.g. "10 GB"
  data_amount_gb numeric(8,2) not null,
  price_ghc numeric(10,2) not null,
  is_active boolean default true,
  sort_order int default 0,
  created_at timestamp with time zone default now()
);

comment on table bundles is 'Available data bundle packages for all networks';
comment on column bundles.network is 'Network: MTN, AT_ISHARE, AT_BIGTIME, TELECEL, MTN_UP2U';
comment on column bundles.display_name is 'Display name shown to users (e.g., "10 GB")';
comment on column bundles.data_amount_gb is 'Data amount in gigabytes';
comment on column bundles.price_ghc is 'Price in Ghanaian Cedis';
comment on column bundles.is_active is 'Whether this bundle is currently available for purchase';
comment on column bundles.sort_order is 'Display order (lower numbers first)';

-- =====================================================
-- 5. Enable Row Level Security (RLS)
-- =====================================================
alter table profiles enable row level security;
alter table wallet_transactions enable row level security;
alter table orders enable row level security;
alter table bundles enable row level security;

-- =====================================================
-- 6. RLS Policies
-- =====================================================
-- Users can view their own profile
create policy "Users can view own profile" 
  on profiles for select 
  using (auth.uid() = id);

-- Users can update their own profile
create policy "Users can update own profile" 
  on profiles for update 
  using (auth.uid() = id);

-- Users can view their own wallet transactions
create policy "Users can view own transactions" 
  on wallet_transactions for select 
  using (auth.uid() = user_id);

-- Users can view their own orders
create policy "Users can view own orders" 
  on orders for select 
  using (auth.uid() = user_id);

-- Public can view active bundles (no authentication required for browsing)
create policy "Public can view active bundles" 
  on bundles for select 
  using (is_active = true);

-- =====================================================
-- 7. Performance Indexes
-- =====================================================
create index idx_orders_user_id on orders(user_id);
create index idx_orders_status on orders(status);
create index idx_orders_created_at on orders(created_at desc);
create index idx_orders_network on orders(network);
create index idx_wallet_transactions_user_id on wallet_transactions(user_id);
create index idx_wallet_transactions_created_at on wallet_transactions(created_at desc);
create index idx_wallet_transactions_reference on wallet_transactions(reference);
create index idx_bundles_network on bundles(network);
create index idx_bundles_price on bundles(price_ghc);
create index idx_bundles_active on bundles(is_active) where is_active = true;

-- =====================================================
-- 8. Seed Data Bundle Packages
-- =====================================================
-- Insert all available bundles for MTN, AT iShare, AT Big Time, Telecel, and MTN UP2U

insert into bundles (network, display_name, data_amount_gb, price_ghc, sort_order) values

-- MTN UP2U Business
('MTN_UP2U', '1 GB', 1, 6.00, 1),
('MTN_UP2U', '2 GB', 2, 11.00, 2),
('MTN_UP2U', '3 GB', 3, 16.00, 3),
('MTN_UP2U', '4 GB', 4, 21.00, 4),
('MTN_UP2U', '5 GB', 5, 25.00, 5),
('MTN_UP2U', '6 GB', 6, 30.00, 6),
('MTN_UP2U', '8 GB', 8, 40.00, 7),
('MTN_UP2U', '10 GB', 10, 48.00, 8),
('MTN_UP2U', '15 GB', 15, 68.00, 9),
('MTN_UP2U', '20 GB', 20, 89.00, 10),
('MTN_UP2U', '25 GB', 25, 112.00, 11),
('MTN_UP2U', '30 GB', 30, 132.00, 12),
('MTN_UP2U', '40 GB', 40, 179.00, 13),
('MTN_UP2U', '50 GB', 50, 225.00, 14),

-- AT iShare Business
('AT_ISHARE', '1 GB', 1, 5.00, 1),
('AT_ISHARE', '2 GB', 2, 9.00, 2),
('AT_ISHARE', '3 GB', 3, 14.00, 3),
('AT_ISHARE', '4 GB', 4, 28.00, 4),
('AT_ISHARE', '5 GB', 5, 24.00, 5),
('AT_ISHARE', '6 GB', 6, 27.00, 6),
('AT_ISHARE', '8 GB', 8, 36.00, 7),
('AT_ISHARE', '10 GB', 10, 47.00, 8),
('AT_ISHARE', '15 GB', 15, 66.00, 9),
('AT_ISHARE', '20 GB', 20, 79.00, 10),
('AT_ISHARE', '30 GB', 30, 89.00, 11),
('AT_ISHARE', '40 GB', 40, 99.00, 12),
('AT_ISHARE', '50 GB', 50, 118.00, 13),
('AT_ISHARE', '80 GB', 80, 190.00, 14),
('AT_ISHARE', '100 GB', 100, 221.00, 15),

-- AT Big Time Business (same pricing as iShare)
('AT_BIGTIME', '1 GB', 1, 5.00, 1),
('AT_BIGTIME', '2 GB', 2, 9.00, 2),
('AT_BIGTIME', '3 GB', 3, 14.00, 3),
('AT_BIGTIME', '4 GB', 4, 28.00, 4),
('AT_BIGTIME', '5 GB', 5, 24.00, 5),
('AT_BIGTIME', '6 GB', 6, 27.00, 6),
('AT_BIGTIME', '8 GB', 8, 36.00, 7),
('AT_BIGTIME', '10 GB', 10, 47.00, 8),
('AT_BIGTIME', '15 GB', 15, 66.00, 9),
('AT_BIGTIME', '20 GB', 20, 79.00, 10),
('AT_BIGTIME', '30 GB', 30, 89.00, 11),
('AT_BIGTIME', '40 GB', 40, 99.00, 12),
('AT_BIGTIME', '50 GB', 50, 118.00, 13),
('AT_BIGTIME', '80 GB', 80, 190.00, 14),
('AT_BIGTIME', '100 GB', 100, 221.00, 15),

-- Telecel Business (Vodafone)
('TELECEL', '5 GB', 5, 28.00, 1),
('TELECEL', '10 GB', 10, 48.00, 2),
('TELECEL', '15 GB', 15, 69.00, 3),
('TELECEL', '20 GB', 20, 90.00, 4),

-- Regular MTN (if you want to keep a separate regular MTN list – same as UP2U)
('MTN', '1 GB', 1, 6.00, 1),
('MTN', '2 GB', 2, 11.00, 2),
('MTN', '3 GB', 3, 16.00, 3),
('MTN', '4 GB', 4, 21.00, 4),
('MTN', '5 GB', 5, 25.00, 5),
('MTN', '6 GB', 6, 30.00, 6),
('MTN', '8 GB', 8, 40.00, 7),
('MTN', '10 GB', 10, 48.00, 8),
('MTN', '15 GB', 15, 68.00, 9),
('MTN', '20 GB', 20, 89.00, 10),
('MTN', '25 GB', 25, 112.00, 11),
('MTN', '30 GB', 30, 132.00, 12),
('MTN', '40 GB', 40, 179.00, 13),
('MTN', '50 GB', 50, 225.00, 14);

-- Verify bundle insertion
-- Uncomment to run after seeding:
-- select network, count(*) as total_packages from bundles group by network;

-- =====================================================
-- 9. Helper Functions (Optional but useful)
-- =====================================================

-- Function to automatically create profile when user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'phone');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to create profile on user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

comment on function public.handle_new_user() is 'Automatically creates a profile when a new user signs up';

-- =====================================================
-- Schema Setup Complete!
-- =====================================================
-- Tables created:
-- ✅ profiles (user accounts with balance)
-- ✅ wallet_transactions (credit/debit history)
-- ✅ orders (data bundle purchases)
-- ✅ bundles (available data packages - 68 packages seeded)
--
-- Next steps:
-- 1. Verify bundles were inserted: 
--    SELECT network, count(*) as total_packages FROM bundles GROUP BY network;
-- 2. Test the schema by creating a test user
-- 3. Set up your API keys in Supabase secrets
-- 4. Connect your React app to Supabase
-- =====================================================

