-- =====================================================
-- Bundles Table & Seed Data
-- =====================================================
-- Run this if you need to add bundles separately
-- or if you've already created the other tables
-- =====================================================

-- Bundles table
create table if not exists bundles (
  id bigint generated by default as identity primary key,
  network text not null check (network in ('MTN', 'AT_ISHARE', 'AT_BIGTIME', 'TELECEL', 'MTN_UP2U')),
  display_name text not null,        -- e.g. "10 GB"
  data_amount_gb numeric(8,2) not null,
  price_ghc numeric(10,2) not null,
  is_active boolean default true,
  sort_order int default 0,
  created_at timestamp with time zone default now()
);

-- Enable RLS (users can only read active bundles)
alter table bundles enable row level security;

create policy "Public can view active bundles" 
  on bundles for select 
  using (is_active = true);

-- Indexes
create index if not exists idx_bundles_network on bundles(network);
create index if not exists idx_bundles_price on bundles(price_ghc);
create index if not exists idx_bundles_active on bundles(is_active) where is_active = true;

-- Seed all bundles exactly as specified
insert into bundles (network, display_name, data_amount_gb, price_ghc, sort_order) values

-- MTN UP2U Business
('MTN_UP2U', '1 GB', 1, 6.00, 1),
('MTN_UP2U', '2 GB', 2, 11.00, 2),
('MTN_UP2U', '3 GB', 3, 16.00, 3),
('MTN_UP2U', '4 GB', 4, 21.00, 4),
('MTN_UP2U', '5 GB', 5, 25.00, 5),
('MTN_UP2U', '6 GB', 6, 30.00, 6),
('MTN_UP2U', '8 GB', 8, 40.00, 7),
('MTN_UP2U', '10 GB', 10, 48.00, 8),
('MTN_UP2U', '15 GB', 15, 68.00, 9),
('MTN_UP2U', '20 GB', 20, 89.00, 10),
('MTN_UP2U', '25 GB', 25, 112.00, 11),
('MTN_UP2U', '30 GB', 30, 132.00, 12),
('MTN_UP2U', '40 GB', 40, 179.00, 13),
('MTN_UP2U', '50 GB', 50, 225.00, 14),

-- AT iShare Business
('AT_ISHARE', '1 GB', 1, 5.00, 1),
('AT_ISHARE', '2 GB', 2, 9.00, 2),
('AT_ISHARE', '3 GB', 3, 14.00, 3),
('AT_ISHARE', '4 GB', 4, 28.00, 4),
('AT_ISHARE', '5 GB', 5, 24.00, 5),
('AT_ISHARE', '6 GB', 6, 27.00, 6),
('AT_ISHARE', '8 GB', 8, 36.00, 7),
('AT_ISHARE', '10 GB', 10, 47.00, 8),
('AT_ISHARE', '15 GB', 15, 66.00, 9),
('AT_ISHARE', '20 GB', 20, 79.00, 10),
('AT_ISHARE', '30 GB', 30, 89.00, 11),
('AT_ISHARE', '40 GB', 40, 99.00, 12),
('AT_ISHARE', '50 GB', 50, 118.00, 13),
('AT_ISHARE', '80 GB', 80, 190.00, 14),
('AT_ISHARE', '100 GB', 100, 221.00, 15),

-- AT Big Time Business (same pricing as iShare)
('AT_BIGTIME', '1 GB', 1, 5.00, 1),
('AT_BIGTIME', '2 GB', 2, 9.00, 2),
('AT_BIGTIME', '3 GB', 3, 14.00, 3),
('AT_BIGTIME', '4 GB', 4, 28.00, 4),
('AT_BIGTIME', '5 GB', 5, 24.00, 5),
('AT_BIGTIME', '6 GB', 6, 27.00, 6),
('AT_BIGTIME', '8 GB', 8, 36.00, 7),
('AT_BIGTIME', '10 GB', 10, 47.00, 8),
('AT_BIGTIME', '15 GB', 15, 66.00, 9),
('AT_BIGTIME', '20 GB', 20, 79.00, 10),
('AT_BIGTIME', '30 GB', 30, 89.00, 11),
('AT_BIGTIME', '40 GB', 40, 99.00, 12),
('AT_BIGTIME', '50 GB', 50, 118.00, 13),
('AT_BIGTIME', '80 GB', 80, 190.00, 14),
('AT_BIGTIME', '100 GB', 100, 221.00, 15),

-- Telecel Business (Vodafone)
('TELECEL', '5 GB', 5, 28.00, 1),
('TELECEL', '10 GB', 10, 48.00, 2),
('TELECEL', '15 GB', 15, 69.00, 3),
('TELECEL', '20 GB', 20, 90.00, 4),

-- Regular MTN (if you want to keep a separate regular MTN list – same as UP2U)
('MTN', '1 GB', 1, 6.00, 1),
('MTN', '2 GB', 2, 11.00, 2),
('MTN', '3 GB', 3, 16.00, 3),
('MTN', '4 GB', 4, 21.00, 4),
('MTN', '5 GB', 5, 25.00, 5),
('MTN', '6 GB', 6, 30.00, 6),
('MTN', '8 GB', 8, 40.00, 7),
('MTN', '10 GB', 10, 48.00, 8),
('MTN', '15 GB', 15, 68.00, 9),
('MTN', '20 GB', 20, 89.00, 10),
('MTN', '25 GB', 25, 112.00, 11),
('MTN', '30 GB', 30, 132.00, 12),
('MTN', '40 GB', 40, 179.00, 13),
('MTN', '50 GB', 50, 225.00, 14);

-- Confirm insertion
select network, count(*) as total_packages, 
       min(price_ghc) as min_price, 
       max(price_ghc) as max_price
from bundles 
group by network
order by network;

